version: '3.7'
services:
  postgresql:
    image: postgresql:latest
    ports:
      - '3306:9999'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=9mREsvXDs9Gk89Ef
